version: '3.4'

services:
  db:
    image: rest-with-asp-net-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
        TZ: America/Sao_Paulo
        MYSQL_ROOT_PASSWORD: RootPassword
        MYSQL_DATABASE: rest_with_asp_net
        MYSQL_USER: MainUser
        MYSQL_PASSWORD: MainPassword
    volumes:
        - /var/lib/mysql
    ports:
        - 3308:3306
    networks:
        - api-network
      
  rest-with-asp-net:
    image: rest-with-asp-net
    build:
      context: .
      dockerfile: RestWithASPNET/Dockerfile
    environment:
        TZ: America/Sao_Paulo
        ASPNETCORE_ENVIRONMENT: Development
    ports:
        - 44386:80
    depends_on:
        - db
    networks:
        - api-network
networks:
  api-network:
    driver: bridge

    
